FROM python:3.10-slim
WORKDIR /app

COPY requirements_streamlit.txt /app/requirements_streamlit.txt
RUN pip install --no-cache-dir -r /app/requirements_streamlit.txt

COPY app.py /app/app.py

EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]
